apps/adopcion/urls.py
from django.conf.urls import url, include
from apps.adopcion.views import index

urlpatterns = [
    url(r'^$', index),
]

apps/mascota/urls.py
from django.conf.urls import url, include
from apps.mascota.views import index, mascota_view, mascotalista, mascotaeditar, mascotaborrar

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', mascota_view, name='mascota_crear'),
    url(r'^lista$', mascotalista, name='mascota_lista'),
    url(r'^editar/(?P<id_mascota>\d+)/$', mascotaeditar, name='mascota_editar'),
    url(r'^eliminar/(?P<id_mascota>\d+)/$', mascotaborrar, name='mascota_borrar'),
]

misperris/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace="adopcion")),

]

apps/adopcion/models.py
from django.db import models

# Create your models here.

class Persona(models.Model):
    rut= models.CharField(max_length=10)
    nombre = models.CharField(max_length=50)
    apellidop = models.CharField(max_length=50)
    apellidom = models.CharField(max_length=50)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=12)
    email = models.EmailField()
    direccion = models.TextField()

    def __str__(self):
        return '{}'.format(self.nombre + ' ' + self.apellidop + ' ' + self.apellidom)

apps/mascota/models.py
from django.db import models
from apps.adopcion.models import Persona


# Create your models here.
class Raza(models.Model):
    nombre = models.CharField(max_length=50)


RAZSELEC = (
    ('desconocida', 'Desconocida'),
    ('raza1', 'Raza1'),
    ('raza2', 'Raza2'),
    ('raza3', 'Raza3'),
)

ESTSELEC = (
    ('disponible', 'Disponible'),
    ('adoptado', 'Adoptado')
)

class Mascota(models.Model):
    imagen = models.ImageField(upload_to='static/img/rescatados', blank=True)
    nombre = models.CharField(max_length=50)
    raza = models.CharField(max_length=20, choices=RAZSELEC, default='desconocida')
    descripcion = models.TextField(blank=True)
    estado = models.CharField(max_length=20, choices=ESTSELEC, default='adoptado')
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.nombre)

apps/persona/models.py
from django.db import models

# Create your models here.

apps/adopcion/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def index(request):
    return HttpResponse("Index de adopcion")

apps/mascota/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from apps.mascota.form import MascotaForm
from apps.mascota.models import Mascota

# Create your views here.
def index(request):
    return render(request, 'mascota/index.html')

def mascota_view(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST)
        if  form.is_valid():
            form.save()
        return redirect('mascota:index')
    else:
        form = MascotaForm()
        return render(request, 'mascota/formulario.html', {'form':form})

def mascotalista(request):
    mascota = Mascota.objects.all()
    contexto = {'mascotas':mascota}
    return render(request, 'mascota/lista_mascota.html', contexto)

def mascotaeditar(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'GET':
        form = MascotaForm(instance=mascota)
    else:
        form = MascotaForm(request.POST, instance=mascota)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_lista')
    return render(request, 'mascota/formulario.html', {'form':form})

def mascotaborrar(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'POST':
        mascota.delete()
        return redirect('mascota:mascota_lista')
    return render(request, 'mascota/borrar_mascota.html', {'mascota':mascota})

apps/persona/views.py
from django.shortcuts import render

# Create your views here.

templates/base/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block extrahead %}
    <meta charset="utf-8">
    <title>Mis Perris</title>
    <!--Flexbox-->
    <link rel="stylesheet" href="{% static 'css/flexboxgrid.min.css' %}">
    <!--Fuente-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--Fancybox-->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "js/fancybox/jquery.fancybox.min.css" %}"/>
    <!--Slick-->
    <link rel="stylesheet" type="text/css" href="{% static "./slick/slick.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "./slick/slick-theme.css" %}"/>
    <!--jQuery Validation-->
    <link rel="stylesheet" href="https://jqueryvalidation.org/files/demo/site-demos.css">
    <!--General-->
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    {% endblock %}
</head>
<body>
<!--Contenedor general-->
{% block body %}
<div class="container" id="wrapper">
    {% block navbar %}
    <section class="row" id="top">
        <!--Logo-->
        <section class="col-xs-12 col-md-6" id="logo">
            <a href="index.html"> <img src="img/logo.png" alt="Logo Mis Perris"> </a>
        </section>
        <!--Menu-->
        <nav class="col-xs-12 col-md-6">
            <ul>
                <li class="col-xs-12"><a href="index.html">inicio</a></li>
                <li class="col-xs-12"><a href="#coach">quienes somos</a></li>
                <li class="col-xs-12"><a href="#eetcafe">servicios</a></li>
                <li class="col-xs-12"><a href="#">contáctanos</a></li>
            </ul>
        </nav>
    </section>
    {% endblock %}


    {% block content %}
    <!--Resto del sitio-->
    <section class="container" id="content">
        <section id="main">
            <img src="img/perro.png" alt="">
        </section>
        <!--Slider-->
        <div id="slickcont" class="single-item">
            <div><img src="img/adoptados/Tom.jpg"/></div>
            <div><img src="img/adoptados/Apolo.jpg"/></div>
            <div><img src="img/adoptados/Duque.jpg"/></div>
        </div>
        <!--Pie de Slider-->
        <footer class="row">
            <address id="info" class="col-xs-12">
                + 56 9 98765431
            </address>
            <section id="info" class="col-xs-12" id="slogan">
                <p>Rescate y adopción de perros callejeros </p>
            </section>
            <section class="col-xs-12" id="social">
                <ul>
                    <li><a href=""><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href=""><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                    <li><a href=""><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                    <li><a href=""><i class="fa fa-envelope" aria-hidden="true"></i></a></li>
                </ul>
            </section>
        </footer>
        <!-- Seccion contenido -->
        <section class="row" id="coaching">

            <!-- Contenido izquierdo -->
            <section class="col-xs-12 col-md-6" id="left">
                <h2>Rescate</h2>
                <p class="subtitulo">Etapa Uno</p>
                <hr>
                <p>Rescatamos perros en situación de peligro y/o abandono. Los rehabilitamos y los preparamos para
                    buscarles
                    un hogar.
                </p>
                <img src="img/rescate.jpg" alt="Perro Negro">
            </section>

            <!-- Contenido derecho -->
            <section class="col-xs-12 col-md-6" id="right">
                <img src="img/crowfunding.jpg" alt="">
                <h2>CROWDFUNDING</h2>
                <p class="subtitulo">Financiamiento</p>
                <hr>
                <p>
                    Sigue nuestras redes sociales para informarte acerca de las diversas campañas y actividades que
                    realizamos para obtener financiamiento para seguir ayudando.
                </p>
                <button type="button" name="button">CAMPAÑAS</button>
            </section>

        </section>
        <!-- Seccion Adoptar -->
        <section class="row" id="gallery">
            <!-- Contenido izquierdo -->
            <section class="col-xs-4" id="adopleft">
                <div>
                    <a data-fancybox="gallery" href="img/rescatados/Oso.jpg"><img src="img/rescatados/Oso_tn.jpg"/></a>
                </div>
                <div>
                    <a data-fancybox="gallery" href="img/rescatados/Maya.jpg"><img
                            src="img/rescatados/Maya_tn.jpg"/></a>
                </div>
                <div>
                    <a data-fancybox="gallery" href="img/rescatados/Wifi.jpg"><img
                            src="img/rescatados/Wifi_tn.jpg"/></a>
                </div>
            </section>

            <!-- Contenido medio -->
            <section class="col-xs-4" id="adopmid">
                <div>
                    <a data-fancybox="gallery" href="img/rescatados/Chocolate.jpg"><img
                            src="img/rescatados/Chocolate_tn.jpg"/></a>
                </div>
                <div>
                    <a data-fancybox="gallery" href="img/rescatados/Pexel.jpg"><img src="img/rescatados/Pexel_tn.jpg"/></a>
                </div>
            </section>

            <!-- Contenido derecho -->
            <section class="col-xs-4" id="adopright">
                <div>
                    <a data-fancybox="gallery" href="img/rescatados/Bigotes.jpg"><img
                            src="img/rescatados/Bigotes_tn.jpg"/></a>
                </div>

                <div>
                    <a data-fancybox="gallery" href="img/rescatados/Luna.jpg"><img
                            src="img/rescatados/Luna_tn.jpg"/></a>
                </div>

            </section>

        </section>
        {% endblock %}

        {% block footer %}
        <!--Pie de Página-->
        <footer class="row" id="credits">
            <div class="col-xs-12"><p>Desarrollo Web y Mobile</p></div>
            <form class="row" id="formulario" name="formulario" method="get" action="">
                <p>
                <div id="label" class="col-xs-12">
                    <label for="nombre">Nombre:</label>
                </div>
                <div class="col-xs-12">
                    <input type="text" name="nombre" placeholder="Juan Pérez" minlength=”3” size="20"/>
                </div>
                </p>
                <p>
                <div id="label" class="col-xs-12">
                    <label for="correo">Correo:</label>
                </div>
                <div class="col-xs-12">
                    <input type="email" name="correo" placeholder="correo@correo.cl"/>
                </div>
                </p>
                <p>
                <div id="label" class="col-xs-12">
                    <label for="rut">Rut:</label>
                </div>
                <div class="col-xs-12">
                    <input type="text" id="rut" name="rut" placeholder="12345678-9" required
                           oninput="verificarRut(this)"/>
                </div>
                </p>
                <p>
                <div id="label" class="col-xs-12">
                    <label for="telefono">Teléfono:</label>
                </div>
                <div class="col-xs-12">
                    <input type="text" name="telefono" placeholder="+56 9 12345678"/>
                </div>
                </p>
                <p>
                <div id="label" class="col-xs-12">
                    <label for="opcion">Tipo de vivienda</label>
                </div>
                <div class="col-xs-12">
                    <select id="respuesta_pregunta" name="respuesta">
                        <option value="vivienda1" selected="selected">vivienda1</option>
                        <option value="vivienda2">vivienda2</option>
                        <option value="vivienda3">vivienda3</option>
                    </select>
                </div>
                </p>
                <p>
                <div id="label" class="col-xs-12">
                    <label for="mensaje">Mensaje</label>
                </div>
                <div class="col-xs-12">
                    <textarea id="mensaje" name="mensaje" maxlength="140" rows="5"></textarea>
                </div>
                </p>
                <div id="label" class="col-xs-12">
                    <p id="boton_contenedor">
                        <input class="boton_enviar" type="submit" value="Enviar"/>
                    </p>
                </div>
            </form>
        </footer>
    {% endblock %}
    </section>
</div>
{% endblock %}

{% block extrajs %}
<!--jQuery-->
<script src="{% static "js/jquery/jquery-3.3.1.min.js" %}" type="text/javascript"></script>
<script src="js/script.js" type="text/javascript"></script>
<script src="js/scriptvaliation.js" type="text/javascript"></script>
<!--jQuery validation-->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.min.js"></script>
<!--Fancybox-->
<script src="{% static "js/fancybox/jquery.fancybox.min.js" %}" type="text/javascript"></script>
<!--Slick-->
<script src="./slick/slick.min.js" type="text/javascript" charset="utf-8"></script>
<!--Activador Slick .js-->
<script type="text/javascript">

      $('.single-item').slick({
        dots: true,
        adaptiveHeight: true,

        });




</script>
{% endblock %}
</body>
</html>

templates/mascota/borrar_mascota.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de {{ mascota.nombre }}?</h3>
    <button class="btn btn-danger" type="submit">Sí, eliminar</button>
    <a class="btn btn-default" href="{% url 'mascota:mascota_lista' %}">Cancelar</a>
</form>


{% endblock %}


{% block footer %}

{% endblock %}

templates/mascota/formulario.html
{% extends 'base/base.html' %}


{% block content %}


{% endblock %}

{% block footer %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
{% endblock %}

templates/mascota/index.html
{% extends 'base/base.html' %}


{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}

templates/mascota/lista_mascota.html
{% extends 'base/base.html' %}


{% block content %}
<table>
    <thead>
    <tr>
        <td>Foto</td>
        <td>Nombre</td>
        <td>Raza</td>
        <td>Descripción</td>
        <td>Estado</td>
        <td>Persona</td>
        <td>Acciones</td>
    </tr>
    </thead>

    <tbody>
    {% if mascotas %}
    {% for mascota in mascotas %}
    <tr>
        <td><img src="../{{ mascota.imagen }}"></td>
        <td>{{ mascota.nombre }}</td>
        <td>{{ mascota.raza }}</td>
        <td>{{ mascota.descripcion }}</td>
        <td>{{ mascota.estado }}</td>
        <td>{{ mascota.persona.nombre }} {{ mascota.persona.apellidop }} {{ mascota.persona.apellidom }}</td>
        <td>
            <a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
            <a class="btn btn-primary" href="{% url 'mascota:mascota_borrar' mascota.id %}">Eliminar</a>
        </td>
    </tr>
    {% endfor %}
    {% else %}
    <h1>No hay ninguna cochiná de perro</h1>
    {% endif %}
    </tbody>
</table>
{% endblock %}

{% block footer %}

{% endblock %}